version: "3"
services:
  #PHP Service
 todo-authorization:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: todo-authorization
    restart: unless-stopped
    tty: true
    environment:
      APP_KEY: base64:20KjR77mhPY0DjEziiRYR+U2FrWvZSHfX6MVcHaMhPg=
      SERVICE_NAME: todo-authorization
      SERVICE_TAGS: dev
      DB_HOST: todo-authorization-db
      DB_DATABASE: todo-authorization-db
      DB_PASSWORD: passwd
      DB_PORT: "3306"
      DB_USERNAME: root
      APP_ENV: local
      APP_URL: todo-webserver-authorization
      LOGIN_URL: todo-webserver-authorization
      APP_DEBUG: "true"
      APP_LOG_LEVEL: debug
      AUTHORIZATION_URL: /oauth/authorize
      TOKEN_URL: /oauth/token
      REFRESH_URL: /oauth/token/refresh
      TOKEN_EXPIRY_HOURS: 3
      ACCEPTED_SECRETS : "[gatwaySecret]"
      MAIL_MAILER : smtp
      MAIL_HOST : sandbox.smtp.mailtrap.io
      MAIL_PORT : 2525
      MAIL_USERNAME: 1b98c7e3c5f851
      MAIL_PASSWORD: c234e6db71df88
      MAIL_ENCRYPTION : 
      
    ports:
      - 6023:80
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./dockerfiles/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - todo-network
    command: bash -c "
      (composer install || true) &&
      (php artisan migrate --seed || true) &&
      (php artisan config:cache || true) &&
      (php artisan route:clear || true)  &&
      (nginx -t && nginx) &&
      php-fpm"

 todo-authorization-db:
    image: mysql:5.7.22
    container_name: todo-authorization-db
    restart: unless-stopped
    tty: true
    ports:
      - "33077:3306"
    environment:
          MYSQL_DATABASE: todo-authorization-db
          MYSQL_ROOT_PASSWORD: "passwd"
          SERVICE_TAGS: dev
          SERVICE_NAME: mysql
    volumes:
    - dbdata:/var/www

    networks:
      - todo-network
  #Nginx Service
 todo-webserver-authorization:
    image: nginx:alpine
    container_name: todo-webserver-authorization
    restart: unless-stopped
    tty: true
    ports:
      - "3080:80"
    volumes:
      - ./:/var/www
      - ./dockerfiles/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
        - todo-network
#Docker Networks
networks:
  todo-network:
    external: true
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local

