version: "3"
services:
  #PHP Service
  todo-authorization-ms:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: digitalocean.com/php
    container_name: todo-authorization-ms
    restart: unless-stopped
    tty: true
    environment:
      APP_NAME : todo-authorization-ms
      APP_KEY: base64:20KjR77mhPY0DjEziiRYR+U2FrWvZSHfX6MVcHaMhPg=
      SERVICE_NAME: todo-authorization-ms
      SERVICE_TAGS: dev
      DB_HOST: todo-db
      DB_DATABASE: todo-authorization-db
      DB_PASSWORD: passwd
      DB_PORT: "3306"
      DB_USERNAME: root
      APP_ENV: local
      APP_DEBUG: "true"
      APP_LOG_LEVEL: debug
      LOGIN_URL: todo-authorization-ms
      AUTHORIZATION_URL: /oauth/authorize
      TOKEN_URL: /oauth/token
      REFRESH_URL: /oauth/token/refresh
      TOKEN_EXPIRY_HOURS: 3
      ACCEPTED_SECRETS : "gatwaySecret,gatwaySecret1"
      QUEUE_DRIVER: redis
      QUEUE_CONNECTION: redis
      TASK_MANAGAMENT_MS_REDIS_HOST: redis
      REDIS_CLIENT: predis
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      BROADCAST_DRIVER : redis
      MAIL_MAILER : smtp
      MAIL_HOST : sandbox.smtp.mailtrap.io
      MAIL_PORT : 2525
      MAIL_USERNAME: 1b98c7e3c5f851
      MAIL_PASSWORD: c234e6db71df88
      MAIL_ENCRYPTION : 
    ports:
      - 6023:80
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./localDockerfiles/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - todo-network
    command: bash -c "
      (composer install || true) &&
      (php artisan migrate --seed || true) &&
      (php artisan config:cache || true) &&
      (php artisan route:clear || true)  &&
      (nginx -t && nginx) &&  chown -R www-data:www-data   /var/www/storage/*  /var/www/bootstrap/cache  &&  chmod +x /var/www/start-supervisor.sh &&
       ./start-supervisor.sh &&  php-fpm"



#Docker Networks
networks:
  todo-network:
    external: true
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local

