version: "3"
services:
  #PHP Service
 todo-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: todo-gateway
    restart: unless-stopped
    tty: true
    depends_on:
      - todo-gateway-db
    environment:
      APP_KEY: base64:20KjR77mhPY0DjEziiRYR+U2FrWvZSHfX6MVcHaMhPg=
      SERVICE_NAME: todo-gateway
      SERVICE_TAGS: dev
      DB_HOST: todo-gateway-db
      DB_DATABASE: todo-gateway-db
      DB_PASSWORD: passwd
      DB_PORT: "3306"
      DB_USERNAME: root
      APP_ENV: local
      APP_URL: todo-webserver-gatway
      APP_DEBUG: "true"
      APP_LOG_LEVEL: debug
      MS_AUTHORIZATION_URL: todo-authorization
      MS_TODO_URL: task-management-ms
    ports:
      - 6020:80
    working_dir: /var/www
    volumes:
      - ./dockerfiles/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - todo-network
    command: bash -c "
      (composer install || true) &&
      (php artisan migrate || true) &&
      (php artisan config:cache || true) &&
      (php artisan route:clear || true)  &&
      (nginx -t && nginx) &&
      php-fpm"

 todo-gateway-db:
    image: mysql:5.7.22
    container_name: todo-gateway-db
    restart: unless-stopped
    tty: true
    ports:
      - "33070:3306"
    environment:
          MYSQL_DATABASE: todo-gateway-db
          MYSQL_ROOT_PASSWORD: "passwd"
          SERVICE_TAGS: dev
          SERVICE_NAME: mysql
    volumes:
    - dbdata:/var/www

    networks:
      - todo-network
  #Nginx Service
 todo-webserver-gatway:
    image: nginx:alpine
    container_name: todo-webserver-gatway
    restart: unless-stopped
    tty: true
    ports:
      - "3098:80"
    volumes:
      - ./:/var/www
      - ./dockerfiles/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
        - todo-network
#Docker Networks
networks:
  todo-network:
    external: true
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local

