version: "3"
services:
  #PHP Service
  todo-gateway:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: digitalocean.com/php
    container_name: todo-gateway
    restart: unless-stopped
    tty: true
    depends_on:
      - todo-db
    environment:
      APP_KEY: base64:20KjR77mhPY0DjEziiRYR+U2FrWvZSHfX6MVcHaMhPg=
      SERVICE_NAME: todo-gateway
      SERVICE_TAGS: dev
      DB_HOST: todo-db
      DB_DATABASE: todo-gateway-db
      DB_PASSWORD: passwd
      DB_PORT: "3306"
      DB_USERNAME: root
      APP_ENV: local
      MS_AUTHORIZATION_URL: todo-authorization-ms
      MS_TODO_URL: task-management-ms
      APP_DEBUG: "true"
      APP_LOG_LEVEL: debug
      ACCEPTED_SECRETS: "secret1,secret2,secret3" 
      AUTHORS_SECRET : "gatwaySecret"

    ports:
      - 6021:80
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./localDockerfiles/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - todo-network
    command: bash -c "
      (composer install || true) &&
      (php artisan migrate || true) &&
      (php artisan config:cache || true) &&
      (php artisan route:clear || true)  &&
       (nginx -t && nginx) &&  chown -R www-data:www-data   /var/www/storage/*  /var/www/bootstrap/cache &&
      php-fpm"

  todo-db:
    image: mysql:5.7.22
    container_name: todo-db
    restart: unless-stopped
    tty: true
    ports:
      - "33070:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "passwd"

    volumes:
      - ./localDockerfiles/provision/mysql/init:/docker-entrypoint-initdb.d   
      - dbdata:/var/www 
    networks:
      - todo-network

#Docker Networks
networks:
  todo-network:
    external: true
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local

