version: "3"
services:
  #PHP Service
  task-management-ms:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: digitalocean.com/php
    container_name: task-management-ms
    restart: unless-stopped
    tty: true
   
    environment:
      APP_KEY: base64:20KjR77mhPY0DjEziiRYR+U2FrWvZSHfX6MVcHaMhPg=
      SERVICE_NAME: task-management-ms
      SERVICE_TAGS: dev
      DB_HOST: todo-db
      DB_DATABASE: task-management-db
      DB_PASSWORD: passwd
      DB_PORT: "3306"
      DB_USERNAME: root
      APP_ENV: local
      APP_DEBUG: "true"
      APP_LOG_LEVEL: debug
      QUEUE_DRIVER: redis
      QUEUE_CONNECTION: redis
      REDIS_CLIENT: predis
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      BROADCAST_DRIVER : redis
    ports:
      - 6022:80
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./localDockerfiles/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - todo-network
    command: bash -c "
      (composer install || true) &&
      (php artisan migrate || true) &&
      (php artisan config:cache || true) &&
      (php artisan route:clear || true)  &&
      (nginx -t && nginx) &&
      php-fpm"

  # Redis Service
  redis:
    image: redis:latest
    container_name: task-management-redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - todo-network

#Docker Networks
networks:
  todo-network:
    external: true
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local

